@echo OFF
set date=%date:~0,10%
set date=%date:-=%
set date=%date:/=%
set time=%time:~0,8%
set time=%time::=%
if "%time:~0,1%"==" " set "time=0%time:~1%"
for /f "delims=" %%i in ('hostname') do set name=%%i
echo 脚本执行中，请稍等片刻......
for /f %%a in ('cscript getIp.vbs //nologo //e:vbscript') do set "realIp=%%a"
if "%realIp%"=="" exit
set result=%~dp0%realIp%_%date%%time%.result
echo equipment_type=HOST_WINDOWS 2>&1 | more > "%result%"
echo #equipment_name# 2>&1 | more >> "%result%"
hostname 2>&1 | more >> "%result%"
echo #equipment_name# 2>&1 | more >> "%result%"
echo #equipment_ip# 2>&1 | more >> "%result%"
echo %realIp% 2>&1 | more >> "%result%"
echo #equipment_ip# 2>&1 | more >> "%result%"
echo cm_item_code=#%%SEC-CI-HT-01#%%SEC-CI-HT-03#%%  2>&1 | more >> "%result%"
echo cm_item_code=#%%SEC-CI-HT-4178#%% 2>&1 | more >> "%result%"
echo cm_item_code=#%%SEC-CI-HT-02#%% 2>&1 | more >> "%result%"
echo cm_item_code=#%%SEC-CI-HT-12#%% 2>&1 | more >> "%result%"
echo cm_item_code=#%%SEC-CI-HT-13#%% 2>&1 | more >> "%result%"
echo cm_item_code=#%%SEC-CI-HT-14#%% 2>&1 | more >> "%result%"
echo cm_item_code=#%%SEC-CI-HT-26#%%SEC-CI-HT-08#%%SEC-CI-HT-05#%%SEC-CI-HT-07#%%SEC-CI-HT-25#%%SEC-CI-HT-09#%%SEC-CI-HT-10#%%SEC-CI-HT-4190#%%SEC-CI-HT-27#%%SEC-CI-HT-06#%%SEC-CI-HT-04#%%SEC-CI-HT-4175#%%SEC-CI-HT-4176#%%SEC-CI-HT-4185#%%SEC-CI-HT-4186#%%SEC-CI-HT-4189#%%SEC-CI-HT-4187#%%SEC-CI-HT-4188#%%  2>&1 | more >> "%result%"
echo cm_item_code=#%%SEC-CI-HT-18#%% 2>&1 | more >> "%result%"
echo cm_item_code=#%%SEC-CI-HT-19#%% 2>&1 | more >> "%result%"
echo cm_item_code=#%%SEC-CI-HT-21#%% 2>&1 | more >> "%result%"
echo cm_item_code=#%%SEC-CI-HT-22#%% 2>&1 | more >> "%result%"
echo cm_item_code=#%%SEC-CI-HT-15#%% 2>&1 | more >> "%result%"
echo cm_item_code=#%%SEC-CI-HT-24#%% 2>&1 | more >> "%result%"
echo cm_item_code=#%%SEC-CI-HT-4174#%% 2>&1 | more >> "%result%"
echo cm_item_code=#%%SEC-CI-HT-4173#%% 2>&1 | more >> "%result%"
echo cm_item_code=#%%SEC-CI-HT-4172#%% 2>&1 | more >> "%result%"
echo cm_item_code=#%%SEC-CI-HT-4177#%% 2>&1 | more >> "%result%"
echo cm_item_code=#%%SEC-CI-HT-4179#%% 2>&1 | more >> "%result%"
echo cm_item_code=#%%SEC-CI-HT-4181#%% 2>&1 | more >> "%result%"
echo cm_item_code=#%%SEC-CI-HT-4183#%% 2>&1 | more >> "%result%"
echo cm_item_code=#%%SEC-CI-HT-4182#%% 2>&1 | more >> "%result%"
echo cm_item_code=#%%SEC-CI-HT-4184#%% 2>&1 | more >> "%result%"
echo cm_item_code=#%%SEC-CI-HT-4180#%% 2>&1 | more >> "%result%"

echo #%%SEC-CI-HT-26#%%SEC-CI-HT-08#%%SEC-CI-HT-05#%%SEC-CI-HT-07#%%SEC-CI-HT-25#%%SEC-CI-HT-09#%%SEC-CI-HT-10#%%SEC-CI-HT-4190#%%SEC-CI-HT-27#%%SEC-CI-HT-06#%%SEC-CI-HT-04#%%SEC-CI-HT-4175#%%SEC-CI-HT-4176#%%SEC-CI-HT-4185#%%SEC-CI-HT-4186#%%SEC-CI-HT-4189#%%SEC-CI-HT-4187#%%SEC-CI-HT-4188#%% 2>&1 | more >> "%result%"
secedit /export /cfg sec.inf /quiet 2>&1 | more >> "%result%"
type sec.inf 2>&1 | more >> "%result%"
del sec.inf 2>&1 | more >> "%result%"
echo #%%SEC-CI-HT-26#%%SEC-CI-HT-08#%%SEC-CI-HT-05#%%SEC-CI-HT-07#%%SEC-CI-HT-25#%%SEC-CI-HT-09#%%SEC-CI-HT-10#%%SEC-CI-HT-4190#%%SEC-CI-HT-27#%%SEC-CI-HT-06#%%SEC-CI-HT-04#%%SEC-CI-HT-4175#%%SEC-CI-HT-4176#%%SEC-CI-HT-4185#%%SEC-CI-HT-4186#%%SEC-CI-HT-4189#%%SEC-CI-HT-4187#%%SEC-CI-HT-4188#%% 2>&1 | more >> "%result%"
echo #%%SEC-CI-HT-01#%%SEC-CI-HT-03#%% 2>&1 | more >> "%result%"
net localgroup administrators|findstr /V "^$ ^别名 ^注释 ^- ^成员 ^命令成功完成"|find /v /n "::" 2>&1 | more >> "%result%"
net localgroup|find "*" |findstr /n "*" 2>&1 | more >> "%result%"
echo #%%SEC-CI-HT-01#%%SEC-CI-HT-03#%% 2>&1 | more >> "%result%"
echo #%%SEC-CI-HT-4178#%% 2>&1 | more >> "%result%"
net localgroup|find "*" |findstr /n "*" 2>&1 | more >> "%result%"
echo #%%SEC-CI-HT-4178#%% 2>&1 | more >> "%result%"
echo #%%SEC-CI-HT-02#%% 2>&1 | more >> "%result%"
net user guest|findstr /r "Account active 帐户启用" 2>&1 | more >> "%result%"
net user guest|findstr /r "active" 2>&1 | more >> "%result%"
echo #%%SEC-CI-HT-02#%% 2>&1 | more >> "%result%"
echo #%%SEC-CI-HT-18#%% 2>&1 | more >> "%result%"
reg query "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\SNMP\Parameters\ValidCommunities" 2>&1 | more >> "%result%"
echo #%%SEC-CI-HT-18#%% 2>&1 | more >> "%result%"
echo #%%SEC-CI-HT-12#%% 2>&1 | more >> "%result%"
chcp 936 2>&1 | more >> "%result%"
netsh firewall show state 2>&1 | more >> "%result%"
echo #%%SEC-CI-HT-12#%% 2>&1 | more >> "%result%"
echo #%%SEC-CI-HT-21#%% 2>&1 | more >> "%result%"
reg query HKLM\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer | find "NoDriveTypeAutoRun" 2>&1 | more >> "%result%"
echo #%%SEC-CI-HT-21#%% 2>&1 | more >> "%result%"

echo #%%SEC-CI-HT-13#%% 2>&1 | more >> "%result%"
tasklist 2>&1 | more >> "%result%"
echo #%%SEC-CI-HT-13#%% 2>&1 | more >> "%result%"
echo #%%SEC-CI-HT-14#%%SEC-CI-HT-4177#%% 2>&1 | more >> "%result%"
secedit /export /cfg sec_EventAudit.inf 2>&1 | more >> "%result%"
type sec_EventAudit.inf|findstr "^Audit" 2>&1 | more >> "%result%"
del sec_EventAudit.inf 2>&1 | more >> "%result%"
echo #%%SEC-CI-HT-14#%%SEC-CI-HT-4177#%% 2>&1 | more >> "%result%"

echo #%%SEC-CI-HT-22#%% 2>&1 | more >> "%result%"
reg query "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\lanmanserver\parameters"|findstr /I "AutoShareServer" 2>&1 | more >> "%result%"
wmic share list; 2>&1 | more >> "%result%"
echo #%%SEC-CI-HT-22#%% 2>&1 | more >> "%result%"
echo #%%SEC-CI-HT-24#%% 2>&1 | more >> "%result%"
wmic logicaldisk where Drivetype=3 get DeviceID, FileSystem 2>&1 | more >> "%result%"
echo #%%SEC-CI-HT-24#%% 2>&1 | more >> "%result%"
echo #%%SEC-CI-HT-19#%% 2>&1 | more >> "%result%"
reg query "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Terminal Server\Wds\rdpwd\Tds\tcp" /v PortNumber 2>&1 | more >> "%result%"
reg query "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp" /v PortNumber 2>&1 | more >> "%result%"
echo #%%SEC-CI-HT-19#%% 2>&1 | more >> "%result%"
echo #%%SEC-CI-HT-4174#%%SEC-CI-HT-4172#%% 2>&1 | more >> "%result%"
(systeminfo || wmic os get Caption,CSDVersion,ServicePackMajorVersion,ServicePackMinorVersion)|findstr /r "^OS 修补程序 Hotfix(s) KB Service Pack"; 2>&1 | more >> "%result%"
echo #%%SEC-CI-HT-4174#%%SEC-CI-HT-4172#%% 2>&1 | more >> "%result%"
echo #%%SEC-CI-HT-4173#%% 2>&1 | more >> "%result%"
wmic NICCONFIG get IPAddress,IPEnabled,IPFilterSecurityEnabled,IPSecPermitIPProtocols,IPSecPermitTCPPorts,IPSecPermitUDPPorts|findstr "TRUE IPAddress"; 2>&1 | more >> "%result%"
echo #%%SEC-CI-HT-4173#%% 2>&1 | more >> "%result%"
echo #%%SEC-CI-HT-4179#%% 2>&1 | more >> "%result%"
net time /QUERYSNTP; 2>&1 | more >> "%result%"
echo #%%SEC-CI-HT-4179#%% 2>&1 | more >> "%result%"
echo #%%SEC-CI-HT-4181#%% 2>&1 | more >> "%result%"
wmic OS Get DataExecutionPrevention_SupportPolicy 2>&1 | more >> "%result%"
bootcfg 2>&1 | more >> "%result%"
echo #%%SEC-CI-HT-4181#%% 2>&1 | more >> "%result%"
echo #%%SEC-CI-HT-4183#%% 2>&1 | more >> "%result%"
wmic DESKTOP get Name,ScreenSaverSecure,ScreenSaverTimeout |findstr /v /b NT.* | findstr /v \\.DEFAULT | findstr /v postgres; 2>&1 | more >> "%result%"
echo #%%SEC-CI-HT-4183#%% 2>&1 | more >> "%result%"
echo #%%SEC-CI-HT-4182#%% 2>&1 | more >> "%result%"
reg query "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters"|findstr /I "SynAttackProtect TcpMaxPortsExhausted TcpMaxHalfOpen TcpMaxHalfOpenRetried" 2>&1 | more >> "%result%"
echo #%%SEC-CI-HT-4182#%% 2>&1 | more >> "%result%"
echo #%%SEC-CI-HT-4184#%% 2>&1 | more >> "%result%"
reg query "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\InetStp" /v "VersionString" 2>&1 | more >> "%result%"
echo #%%SEC-CI-HT-4184#%% 2>&1 | more >> "%result%"
echo #%%SEC-CI-HT-4180#%% 2>&1 | more >> "%result%"
wmic nteventlog get Caption,FileSize,MaxFileSize,OverWritePolicy,OverwriteOutDated 2>&1 | more >> "%result%"
echo #%%SEC-CI-HT-4180#%% 2>&1 | more >> "%result%"
echo #%%SEC-CI-HT-15#%% 2>&1 | more >> "%result%"
secedit /export /cfg sec.inf /quiet 2>&1 | more >> "%result%"
type sec.inf 2>&1 | more >> "%result%"
del sec.inf 2>&1 | more >> "%result%"
echo #%%SEC-CI-HT-15#%% 2>&1 | more >> "%result%"




